### PR TITLE
added support for including Battenberg LOH

### PR DESCRIPTION
**Pull request by rdmorin**
This is a minor change and is backwards-compatible with the previous version. I didn't change the version number because I didn't feel it was worth it. If @BrunoGrandePhD feels strongly that it should have the number increased (1.1?) I would be OK with that.

### CODE REVIEW

**Comment by BrunoGrandePhD** [comment]
I think it's best to consider each version merged into master as being frozen. So, I would submit this as a separate version. Here's how you can easily do this:
```bash
# Rename the current version to 1.1
mv cnv2igv/1.0 cnv2igv/1.1

# Recreate version 1.0 from what's on master
git checkout origin/master -- cnv2igv/1.0
```

**Comment by rdmorin** [comment]
```
git checkout origin/master -- cnv2igv/1.0
error: pathspec 'cnv2igv/1.0' did not match any file(s) known to git

**Comment by BrunoGrandePhD** [comment]
Are you running the command from the root of the repo?

**Comment by rdmorin** [comment]
🤦

**Comment by rdmorin** [comment]
Ruh roh:
```
(base) -bash-4.2$ git commit -m "version bump"
[cnv2igv de1c6a0] version bump
 3 files changed, 297 insertions(+), 19 deletions(-)
 create mode 100755 cnv2igv/1.1/cnv2igv.py
 create mode 120000 cnv2igv/1.1/python-3.8.3.yaml
(base) -bash-4.2$ git push
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 144 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 502 bytes | 251.00 KiB/s, done.
Total 5 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/LCR-BCCRC/lcr-scripts.git
   ec122ec..de1c6a0  cnv2igv -> cnv2igv
error: update_ref failed for ref 'refs/remotes/origin/cnv2igv': cannot lock ref 'refs/remotes/origin/cnv2igv': 'refs/remotes/origin/cnv2igv/1.0' exists; cannot create 'refs/remotes/origin/cnv2igv'

**Comment by BrunoGrandePhD** [comment]
The error mentions two branches: `cnv2igv/1.0` and `cnv2igv`. Do you get the same error if you run `git push origin cnv2igv` (_i.e._ restricting the push to the current branch)? In other words, can you confirm that your latest commits on this branch are on GitHub?

https://github.com/LCR-BCCRC/lcr-scripts/tree/cnv2igv

**Comment by rdmorin** [comment]
git push origin cnv2igv
error: update_ref failed for ref 'refs/remotes/origin/cnv2igv': cannot lock ref 'refs/remotes/origin/cnv2igv': 'refs/remotes/origin/cnv2igv/1.0' exists; cannot create 'refs/remotes/origin/cnv2igv'
Everything up-to-date

**Comment by BrunoGrandePhD** [comment]
What's the working directory? I want to check a few things with the repo.

**Comment by rdmorin** [comment]
```
/home/rmorin/lcr-modules-battenberg/lcr-scripts

**Comment by BrunoGrandePhD** [comment]
I noticed this when running `git status`:
```
Your branch is based on 'origin/cnv2igv', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)

nothing to commit, working tree clean
```
Can you try running this?
```
git branch --unset-upstream
git push origin cnv2igv
```

**Comment by rdmorin** [comment]
(base) -bash-4.2$ git branch --unset-upstream
(base) -bash-4.2$ git push origin cnv2igv
error: update_ref failed for ref 'refs/remotes/origin/cnv2igv': cannot lock ref 'refs/remotes/origin/cnv2igv': 'refs/remotes/origin/cnv2igv/1.0' exists; cannot create 'refs/remotes/origin/cnv2igv'
Everything up-to-date

**Comment by BrunoGrandePhD** [comment]
I think I found a solution. Can you run the two commands in the link below and then re-try the `git push`?

https://stackoverflow.com/a/7348934/1615670

**Comment by rdmorin** [comment]
git push
fatal: The current branch cnv2igv has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin cnv2igv

**Comment by BrunoGrandePhD** [comment]
Sorry, I should have been explicit: Run the `git push` command I listed earlier. Because it's complaining about not being linked to the remote branch, you can the `--set-upstream` to create that link. 
```
git push --set-upstream origin cnv2igv
```

**Comment by rdmorin** [comment]
Thanks. I think it worked this time.

**Pull request merged**
