### PR TITLE
allow NAs in subsetting categories

### PR DESCRIPTION
**Pull request by Kdreval**
This is to address #61

### CODE REVIEW

**Comment by Kdreval** [comment]
Sorry Sierra I was on your branch when committed these :facepalm:

**Comment by gillissierra** [comment]
No worries! Was this tested with both "blank" and "NA" values in the level3_subsetting_categories.tsv? It works with both in theory but I like see it just to make sure.

**Comment by Kdreval** [comment]
I tested it with blank, but not NAs

**Comment by Kdreval** [comment]
When it's blank, the read_tsv will auto-populate it with NA - or do you mean put the actual "NA" string into the subsetting categories file? I can try that 😄

**Comment by gillissierra** [comment]
Yes sorry, that's what I meant. But no need, I see one used here https://github.com/morinlab/gambl/pull/316
So it's already been tested.

**Review by gillissierra — APPROVED** [review]

**Pull request merged**
