### PR TITLE
Cnv2igv/1.0

### PR DESCRIPTION
**Pull request by rdmorin**
Prasath's script with a modification to allow processing Battenberg outputs. This version has been tested on Battenberg outputs from both chr prefixed and unprefixed genomes.

### CODE REVIEW

**Comment by rdmorin** [comment]
It would be extremely helpful if this could be merged with master. Please let me know if there are any issues with how I've set up the current version @BrunoGrandePhD .

**Comment by BrunoGrandePhD** [comment]
I'll give this script a quick test on some Sequenza data. In the meantime, could you add a plain Python 3 conda environment into `envs/` and symlink it into `cnv2igv/1.0/`?

**Comment by rdmorin** [comment]
I wasn't entirely sure what naming you wanted for this generic environment. Is this OK?

**Comment by BrunoGrandePhD** [comment]
I prefer to be as specific as possible with the version numbers (in this case, version `3.8.3`). I also omit the build IDs from the conda environment using `conda env export --no-builds`. I did it manually here. 
```
.
├── README.md
├── cnv2igv
│   └── 1.0
│       ├── cnv2igv.py
│       └── python-3.8.3.yaml -> ../../envs/python/python-3.8.3.yaml
├── envs
│   ├── augment_manta_vcf
│   │   └── augment_manta_vcf-1.yaml
│   ├── generate_igv_batch
│   │   └── generate_igv_batch-1.yaml
│   ├── python
│   │   └── python-3.8.3.yaml
│   └── pyvcf
│       └── pyvcf-0.6.8.yaml
```

The PR is ready to be merged!

**Comment by rdmorin** [comment]
:facepalm: I always forget the --no-builds flag

**Pull request merged**
