### PR TITLE
get_bams update

### PR DESCRIPTION
**Pull request by lkhilton**
This version of get_bams.R is less likely to error out and instead produces informative warnings. I've also added an R function version of this, which can be used in the context of other R scripts.

### CODE REVIEW

**Review by rdmorin — COMMENTED** [review]
It looks like get_bams_function.R is sharing most of the same code as get_bams.R. This seems like it will be problematic to maintain. Can get_bams.R be replaced with a simple script that retains the original functionality of the current script but runs get_bams_function.R under the hood?

**Comment by lkhilton** [comment]
Great idea. I will implement that.

**Comment by lkhilton** [comment]
I implemented that change in v1.1 and tested it thoroughly.

**Review by rdmorin — APPROVED** [review]
:delicioso:

**Pull request merged**
