### PR TITLE
generate_igv_batch version 2.0

### PR DESCRIPTION
**Pull request by BrunoGrandePhD**

### CODE REVIEW

**Comment by BrunoGrandePhD** [comment]
@Jwong684: I quickly tested the script on random files and it seems to work. Could you test it on a random VCF file, a random BED file, a random BEDPE file, and a random MAF file?

**Comment by Jwong684** [comment]
@BrunoGrandePhD  Okay

**Comment by BrunoGrandePhD** [comment]
I just realized that I forgot to add documentation to the script... I'm going to work on that tomorrow morning. I just added a symlink to the same conda environment that was used for v1.0.

**Comment by rdmorin** [comment]
Does this work out of the box with the IGV installed by conda? I never got around to trying that.

**Comment by rdmorin** [comment]
Ignore that last comment. I now recall this only generates the batchfile but does not run IGV. My question relates to any (eventual) snakefiles that run this batch file in IGV.

**Comment by Jwong684** [comment]
All the batch files seem to be generated as intended (I tested .vcf, .bed, .bedpe, single .maf). One thing is that the script does not allow for vcf.gz files at the moment. Multi-maf does not seem to work at the moment - it seems to be loading way too many bam files per region. I'll have to take a look at it later.

I'm not sure how the conda igv would differ from the one we have so far. I'd expect it'd be able to handle the batch file though.

**Comment by rdmorin** [comment]
Different versions of IGV worked variably robustly (or not robustly at all) with running it headless in batch mode with large files

**Comment by BrunoGrandePhD** [comment]
@Jwong684: Could you post the commands and working directory that didn't work? Make sure the files you used as input still exist so I can run the commands.

**Comment by Jwong684** [comment]
dirIn:
`cd /projects/rmorin/projects/RNA_seq_ssm/test/`

`conda activate envs/igvTest`

command:
`python3 generate_igv_batch5.py ddx3x_nonsyn_mutations.rnaseq_only.no_artifact.maf --bam_table ddx3x_bamList2.txt --snapshot_dir ./testOut --genome_build hg38 --output multimaf_test6.batch`

output:
 /projects/rmorin/projects/RNA_seq_ssm/test/multimaf_test5.batch

`TypeError: join() argument must be str or bytes, not 'float'
Traceback (most recent call last):
  File "generate_igv_batch5.py", line 492, in <module>
    main()
  File "generate_igv_batch5.py", line 56, in main
    args.genome_build,
  File "generate_igv_batch5.py", line 463, in generate_igv_batch
    sample_snapshot_dir = os.path.join(snapshot_dir, sample, "")
  File "/home/jawong/software/miniconda3/envs/igvTest/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/jawong/software/miniconda3/envs/igvTest/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None`

It seems like it's just misunderstanding samples that have a decimal in its name (ex. BLGSP-71-19-00128-09A.1-01R).

**Comment by rdmorin** [comment]
Can't you just concatenate the output of os.path (i.e. using string operations) instead? It must be doing something weird and non-stringy here.

**Comment by BrunoGrandePhD** [comment]
@Jwong684: The issue is actually with the input MAF file. For some reason, the tabs in rows 4-6 were converted to spaces. This issue doesn't exist in the file I gave you, so you must have done something that messed up the tab characters. I confirmed that the command works if I switch to my original version. 

I will see if I can configure pandas to warn the user if the input TSV is malformed. 

## Jasper's Version

```
❯ tail -n+2 /projects/rmorin/projects/RNA_seq_ssm/test/ddx3x_nonsyn_mutations.rnaseq_only.no_artifact.maf | tsv

| Hugo_Symbol                                                                      | Entrez_Gene_Id | Center | NCBI_Build | C
| -------------------------------------------------------------------------------- | -------------- | ------ | ---------- | -
| DDX3X                                                                            | 0              |        | GRCh38     | c
| DDX3X   0       .       GRCh38  chrX    41334254        41342454        +    ... |                |        |            |
| DDX3X   0       .       GRCh38  chrX    41334260        41334260        +    ... |                |        |            |
| DDX3X   0       .       GRCh38  chrX    41334280        41334280        +    ... |                |        |            |
| DDX3X                                                                            | 0              |        | GRCh38     | c
| DDX3X                                                                            | 0              |        | GRCh38     | c
| DDX3X                                                                            | 0              |        | GRCh38     | c
| DDX3X                                                                            | 0              |        | GRCh38     | c
| DDX3X                                                                            | 0              |        | GRCh38     | c
| DDX3X                                                                            | 0              |        | GRCh38     | c
| DDX3X                                                                            | 0              |        | GRCh38     | c
| DDX3X                                                                            | 0              |        | GRCh38     | c
| DDX3X                                                                            | 0              |        | GRCh38     | c
| DDX3X                                                                            | 0              |        | GRCh38     | c
```

## Bruno's Original Version

```
❯ less /projects/bgrande/experiments/2020-04-14-ddx3x_rnaseq_variants/ddx3x_nonsyn_mutations.rnaseq_only.no_artifact.maf | tsv
| Hugo_Symbol | Entrez_Gene_Id | Center | NCBI_Build | Chromosome | Start_Position | End_Position | Strand | Variant_Classifi
| ----------- | -------------- | ------ | ---------- | ---------- | -------------- | ------------ | ------ | ----------------
| DDX3X       | 0              |        | GRCh38     | chrX       | 41334254       | 41334254     | +      | Translation_Star
| DDX3X       | 0              |        | GRCh38     | chrX       | 41334295       | 41334295     | +      | Nonsense_Mutatio
| DDX3X       | 0              |        | GRCh38     | chrX       | 41342493       | 41342493     | +      | Splice_Site
| DDX3X       | 0              |        | GRCh38     | chrX       | 41342837       | 41342837     | +      | Splice_Site
| DDX3X       | 0              |        | GRCh38     | chrX       | 41344299       | 41344299     | +      | Nonsense_Mutatio
| DDX3X       | 0              |        | GRCh38     | chrX       | 41344401       | 41344401     | +      | Splice_Site
| DDX3X       | 0              |        | GRCh38     | chrX       | 41344401       | 41344401     | +      | Splice_Site
| DDX3X       | 0              |        | GRCh38     | chrX       | 41345254       | 41345255     | +      | Frame_Shift_Ins
| DDX3X       | 0              |        | GRCh38     | chrX       | 41347349       | 41347349     | +      | Nonsense_Mutatio
| DDX3X       | 0              |        | GRCh38     | chrX       | 41347453       | 41347453     | +      | Splice_Site
| DDX3X       | 0              |        | GRCh38     | chrX       | 41347717       | 41347717     | +      | Nonstop_Mutation

```

**Comment by BrunoGrandePhD** [comment]
I added a docstring for the script (which gets included in the help info at the command line), and I clarified the command-line arguments. Here's what gets printed out when you run the script with `--help`. Any feedback? 

```
❯ generate_igv_batch.py --help
usage: generate_igv_batch.py [-h] [--output OUTPUT_FILE] [--format {maf,bed,bedpe,vcf}] [--bam_table BAM_TABLE_FILE]
                             [--bam_list BAM_FILE_1 [BAM_FILE_2 ...]] [--gene_column GENE_COLUMN_FILE]
                             [--gene_list GENE_1 [GENE_2 ...]] [--padding PADDING] [--max_height MAX_HEIGHT] --snapshot_dir
                             SNAPSHOT_DIR --genome_build GENOME_BUILD [--pass_only]
                             input_file

This script creates IGV batch scripts, which automate the process of taking IGV screenshots for regions of interest (e.g.,
point mutations and structural variations). For more information, check out this link:
https://software.broadinstitute.org/software/igv/batch. The following command will print usage information, including the
various command-line options and the list of supported file formats: generate_igv_batch.py --help; The script takes the
following as inputs: (1) File specifying mutation sites (the list of supported file formats is listed in the usage
information when you run the script with `--help`); (2) List of BAM files, which can be provided at the command line with
`--bam_list` or in a table format using `--bam_table`; (3) (Optional) List of genes to filter on (not all formats are
supported); (4) Additional parameters (check out the help page using `--help` to find out more).

positional arguments:
  input_file            Input file ['maf', 'bed', 'bedpe', 'vcf']. Can be '-' for stdin.

optional arguments:
  -h, --help            show this help message and exit
  --output OUTPUT_FILE, -o OUTPUT_FILE
                        Output IGV batch script. Can be '-' for stdout.
  --format {maf,bed,bedpe,vcf}, -f {maf,bed,bedpe,vcf}
                        Format of the input file. Otherwise, the format will be inferred from the file extension.
  --bam_table BAM_TABLE_FILE, -bt BAM_TABLE_FILE
                        Two-column tab-delimited table mapping sample IDs to BAM files paths.
  --bam_list BAM_FILE_1 [BAM_FILE_2 ...], -bl BAM_FILE_1 [BAM_FILE_2 ...]
                        Space-delimited list of BAM files.
  --gene_column GENE_COLUMN_FILE, -gt GENE_COLUMN_FILE
                        Single-column file with gene symbols (no header). Used to filter input file. Supported formats: MAF.
  --gene_list GENE_1 [GENE_2 ...], -gl GENE_1 [GENE_2 ...]
                        Space-delimited list of gene symbols. Used to filter input file. Supported formats: MAF.
  --padding PADDING, -p PADDING
                        Amount of padding added before and after each locus. Default padding is 300.
  --max_height MAX_HEIGHT, -m MAX_HEIGHT
                        Maximum panel height in IGV. Default max height is 400.
  --snapshot_dir SNAPSHOT_DIR, -d SNAPSHOT_DIR
                        Directory where all of the IGV snapshots will be stored once IGV is run subsequently.
  --genome_build GENOME_BUILD, -g GENOME_BUILD
                        Specify IGV genome build (e.g., 'hg19' or 'hg38')
  --pass_only, -po      Filter for records that have passed any filters. For example, for VCF files, this would filter for
                        mutations where the FILTER column contains 'PASS'. Supported formats: VCF.
```

**Comment by BrunoGrandePhD** [comment]
I also added a check for MAF files to ensure there is no missing data, which would have caught the issue with the malformed MAF file. Here's the output if the error gets triggered:

```
❯ python3 generate_igv_batch/2.0/generate_igv_batch.py /projects/rmorin/projects/RNA_seq_ssm/test/ddx3x_nonsyn_mutations.rnaseq_only.no_artifact.maf --bam_table /projects/rmorin/projects/RNA_seq_ssm/test/ddx3x_bamList2.txt --snapshot_dir ~/testOut --genome_build hg38 --output ~/multimaf_test6.batch
Traceback (most recent call last):
  File "generate_igv_batch/2.0/generate_igv_batch.py", line 555, in <module>
    main()
  File "generate_igv_batch/2.0/generate_igv_batch.py", line 52, in main
    regions = get_regions(
  File "generate_igv_batch/2.0/generate_igv_batch.py", line 408, in get_regions
    return get_regions(input_file, **kwargs)
  File "generate_igv_batch/2.0/generate_igv_batch.py", line 358, in get_regions_maf
    assert not is_any_na, (
AssertionError: The 'Chromosome' column contains NA values. This might be caused by an incorrectly formatted input MAF file. Please ensure that all of the following columns have values: Chromosome, Start_Position, End_Position, Hugo_Symbol, Tumor_Sample_Barcode.Here's a preview of the MAF file after being parsed:

                                           Hugo_Symbol  Entrez_Gene_Id  ... dbSNP_Val_Status         Tumor_Sample_Barcode
0                                               DDX3X             0.0  ...              NaN    BLGSP-71-08-00038-01A-01R
1   DDX3X   0       .       GRCh38  chrX    413342...             NaN  ...              NaN                          NaN
2   DDX3X   0       .       GRCh38  chrX    413342...             NaN  ...              NaN                          NaN
3   DDX3X   0       .       GRCh38  chrX    413342...             NaN  ...              NaN                          NaN
4                                               DDX3X             0.0  ...              NaN    BLGSP-71-19-00116-01A-01R
5                                               DDX3X             0.0  ...              NaN    BLGSP-71-06-00072-01A-11R
6                                               DDX3X             0.0  ...              NaN    BLGSP-71-06-00086-01A-01R
7                                               DDX3X             0.0  ...              NaN  BLGSP-71-19-00128-09A.1-01R
8                                               DDX3X             0.0  ...              NaN    BLGSP-71-19-00125-01A-01R
9                                               DDX3X             0.0  ...              NaN    BLGSP-71-19-00125-09A-01R
10                                              DDX3X             0.0  ...              NaN    BLGSP-71-06-00161-01A-01R
11                                              DDX3X             0.0  ...              NaN    BLGSP-71-06-00165-01A-01R
12                                              DDX3X             0.0  ...              NaN    BLGSP-71-06-00159-01B-01S
13                                              DDX3X             0.0  ...              NaN    BLGSP-71-06-00171-01A-01R

[14 rows x 16 columns]
```

**Comment by BrunoGrandePhD** [comment]
@Jwong684: Were you able to confirm whether the output IGV batch scripts actually work in IGV?

**Comment by Jwong684** [comment]
@BrunoGrandePhD I noticed that the multi-maf batch script writes an "exit" between every new snapshot, which makes it exit the loop prematurely. 
Hm, and doing a couple tests on the other batch files, I realize there's an order mix-up.

So this batch format (from before) work:
`load /projects/rmorin/projects/MCL_genomes/data/STAR_bams/bams_mdups/13-33873_T1.mdups.Aligned.sortedByCoord.out.bam
maxPanelHeight 400
snapshotDirectory /projects/rmorin/projects/RNA_seq_ssm/test/testOut/
genome hg38
goto chr1:16992279-16994443
sort
collapse
snapshot test_removejunction2-chr1:16992279-16994443.png
new
exit`

The new ones seem to print "new" prematurely after loading the genome, so IGV stalls indefinitely:
`load DLC0233.tumour.rnaseq.ucsc_hg19_all.bam
maxPanelHeight 400
snapshotDirectory ./testOut
genome hg19
new
goto chr1:14222-14822
sort
collapse
snapshot chr1:14222-14822--DLC0233.png
new`

**Comment by BrunoGrandePhD** [comment]
@Jwong684: Do you mind fixing the issue? You should be able to clone the repository, checkout the `generate_igv_batch/2.0` branch, and work on the script. Once you fix this, you can commit your changes and push to GitHub, and that will update this PR automatically.

**Comment by Jwong684** [comment]
Okay I'll work on it today

**Comment by BrunoGrandePhD** [comment]
Thanks! If you need input or suggestions, just ask here and I'll get back to you within a few hours.

**Comment by Jwong684** [comment]
I need permission to push to the generate_igv_batch branch.

Troubleshooting note:
- symlinks crash the system
- need to adjust pre-mature exit for multi-maf 
- need to adjust vcf png names to include sample id
- gene-lists, multi-bams, SVs work

**Comment by BrunoGrandePhD** [comment]
> symlinks crash the system
Crash the script or IGV? If the latter, you can use `os.path.realpath()` to resolve the all of the BAM files paths before including them in the iGV batch script. 

> need to adjust pre-mature exit for multi-maf
I pushed a quick fix for this. You can check if it solves the problem. I basically moved the footer code to the end of the `generate_igv_batch()` function rather than the `generate_igv_batch_per_sample()` function. 

> need to adjust vcf png names to include sample id
Will you be getting the sample IDs from the VCF header? If so, which one do you pick if there are more than one? Honestly, most VCF files that we deal with are for a single sample, so I don't think this is that useful, because the user will most likely include the sample ID in the file path of the output file. 

> gene-lists, multi-bams, SVs work
Great!

**Comment by Jwong684** [comment]
Okay everything works like a charm now. Fixed the symlink issue. I'll just need to get permission to push my changes, but we can talk about that in our meeting

Finished testing (works):
-bed
-bedpe
-vcf
-maf
-multi-bam maf with bam-metadata-table
-maf with geneList

**Pull request merged**
